### ISSUE TITLE
Autoregressive Model Checkpoint

### ISSUE THREAD

**Issue by simplewhite9** [antoyang/FrozenBiLM#14]
Hi,

Thank you for the great work!
Is it possible for you to upload the checkpoint for GPT-J-6B as well?

**Comment by antoyang** [comment]
Hey, here it is: https://drive.google.com/file/d/1tv2gWxWFx5rZiHPVRhQ6UYonRQLL08c_/view?usp=sharing (only the non-frozen parameters are included to save some disk space).
