### ISSUE TITLE
Verification code is need for downloading the data features

### ISSUE THREAD

**Issue by junting** [antoyang/FrozenBiLM#2]
Hi @antoyang ,

Thanks a lot for open-sourcing the project! I just got in trouble when trying to download the pre-computed features, since it requires a verification code that seems not provided in the repo.

Best,
Junting

**Comment by antoyang** [comment]
Did you use the bash scripts when trying to download? if so, this may be a verification code that is related to the usage of gshell and not specific to the file.

**Comment by junting** [comment]
Hi,
Thanks for your reply. I did use the bash scripts, and it looks like it is related to the sharing permissions with google drive. I also tried an alternative way using gdown to install the folder, and it reports:
`Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.`


However, it did not happen when used to download the models.

**Comment by ramadasmahale** [comment]
Hi,

I am facing the same issue.  I am not able to download the features as well. 

```
You can’t sign in because project-367116221053 sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384)
If you are a developer of project-367116221053, see [error details](https://accounts.google.com/).
Error 400: invalid_request
```

Can someone please help me out here?

**Comment by antoyang** [comment]
Can you access https://drive.google.com/drive/folders/1ED2VcFSxRW9aFIP2WdGDgLddNTyEVrE5?usp=sharing ? I verified that this link is shared publicly.

**Comment by youseefmoemen** [comment]
I'm having the same issue the link is accessible but I'm still facing the same problem

**Comment by youseefmoemen** [comment]
Thanks a lot

**Comment by vitalyshalumov** [comment]
can you please share the checkpoints using drive.google as you did for the datasets?

**Comment by antoyang** [comment]
Here they are: https://drive.google.com/drive/folders/10Vosd_h6afVf-OSZmwVeTCQReZwpAUJT?usp=sharing
