### ISSUE TITLE
Conda Environment Setting

### ISSUE THREAD

**Issue by wonjiny** [antoyang/FrozenBiLM#6]
Hi.

Instruction says to run "pip install requirements.txt", but it is "pip install -r requirements.txt", right?

And my question is about this error; 

$ pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement clip==1.0 (from versions: 0.0.1, 0.1.0, 0.2.0)
ERROR: No matching distribution found for clip==1.0

How can I download clip==1.0?

**Comment by antoyang** [comment]
Hi, this should be "pip install -r requirements.txt" indeed.
For clip, I think it should work without precising the version ie "pip install clip" (see https://github.com/ZPdesu/Barbershop/issues/18). 
I am going to update the readme and requirements file.
